[workspace]
members = [
    "src/common",
    "src/client",
    "src/server",
    "src/image",
    "entity",
    "migration"
]
exclude = ["snpguest"]
resolver = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
